translations = {
    "Tiếng Việt": {
        "mysql_title": "Đăng nhập MySQL",
        "mysql_label": "Đăng nhập MySQL",
        "db_host": "Máy chủ CSDL:",
        "db_username": "Tên đăng nhập CSDL:",
        "db_password": "Mật khẩu CSDL:",
        "language": "Ngôn ngữ:",
        "login": "Đăng nhập",
        "exit": "Thoát",
        "remember": "Nhớ tôi",
        "user_title": "Đăng nhập người dùng",
        "username": "Tên đăng nhập:",
        "password": "Mật khẩu:",
        "back": "Quay lại",
        "control_title": "Bảng điều khiển",
        "welcome": "Chào mừng",
        "manage": "Quản lý học sinh",
        "attendance": "Điểm danh",
        "export": "Xuất danh sách",
        "edit": "Chỉnh sửa học sinh",
        "quit": "Thoát",
        "logout": "Đăng xuất",
        "no_data": "Không Có Dữ Liệu :(",
        "toggle_dark": "Chuyển sang Dark",
        "toggle_light": "Chuyển sang Light",
        "col_index": "Số Thứ Tự",
        "col_name": "Tên Học Sinh",
        "col_attendance": "Điểm Danh",
        "search": "Tìm kiếm",
        "reason": "Lý do",
        "add_student": "Thêm học sinh",
        "delete_student": "Xoá học sinh",
        "edit_student": "Chỉnh sửa học sinh",
        "set_cutoff": "Cài đặt hạn chót",
        "add_user": "Thêm tài khoản",
        "delete_user": "Xoá tài khoản",
        "edit_user": "Chỉnh sửa tài khoản",
        "user_accounts_tab": "Quản lý tài khoản",
        "students_tab": "Quản lý học sinh",
        "choose_folder": "Chọn thư mục chứa ảnh",
        "invalid_filename_format": "Tên file không hợp lệ. Định dạng yêu cầu: Họ_Tên_Lớp",
        "batch_add_success": "Đã thêm {count} học sinh từ thư mục.",
        "batch_add": "Thêm hàng loạt",
        "add_student_from_image": "Thêm học sinh từ ảnh",
        "browse_image": "Chọn ảnh",
        "camera_header": "Cấu hình Camera",
        "camera_type_label": "Loại kết nối camera:",
        "camera_url_label": "Địa chỉ URL:",
        "simple_mode": "Chế độ đơn giản",
        "connection_mode": "Chế độ kết nối:",
        "camera_username_label": "Tên tài khoản:",
        "camera_password_label": "Mật khẩu:",
        "camera_ip_label": "IP của camera:",
        "camera_port_label": "Cổng:",
        "generate_link": "Tạo link",
        "gmt": "GMT:",
        "cutoff_time": "Hạn chót (HH:MM):",
        "submit": "Gửi",
        "invalid_time_format": "Định dạng giờ không hợp lệ. Vui lòng nhập HH:MM.",
        "cutoff_set_success": "Cài đặt hạn chót thành công.",
    },
    "English": {
        "mysql_title": "MySQL Login",
        "mysql_label": "MySQL Login",
        "db_host": "Database Host:",
        "db_username": "Database Username:",
        "db_password": "Database Password:",
        "language": "Language:",
        "login": "Login",
        "exit": "Exit",
        "remember": "Remember me",
        "user_title": "User Login",
        "username": "Username:",
        "password": "Password:",
        "back": "Back",
        "control_title": "Control Panel",
        "welcome": "Welcome",
        "manage": "Manage Students",
        "attendance": "Attendance",
        "export": "Export List",
        "edit": "Edit Students",
        "quit": "Quit",
        "logout": "Log Out",
        "no_data": "No Data :(",
        "toggle_dark": "Switch to Dark",
        "toggle_light": "Switch to Light",
        "col_index": "STT",
        "col_name": "Student Name",
        "col_attendance": "Attendance",
        "search": "Search",
        "reason": "Reason",
        "add_student": "Add Student",
        "delete_student": "Delete Student",
        "edit_student": "Edit Student",
        "set_cutoff": "Set Cutoff Time",
        "add_user": "Add User",
        "delete_user": "Delete User",
        "edit_user": "Edit User",
        "user_accounts_tab": "User Account Management",
        "students_tab": "Student Management",
        "choose_folder": "Select folder containing images",
        "invalid_filename_format": "Invalid filename format. Required format: Name_Class",
        "batch_add_success": "Added {count} students from folder.",
        "batch_add": "Batch Add",
        "add_student_from_image": "Add Student from Images",
        "browse_image": "Browse Image",
        "camera_header": "Camera Configuration",
        "camera_type_label": "Camera Type:",
        "camera_url_label": "Camera URL:",
        "simple_mode": "Simple Mode",
        "connection_mode": "Connection Type:",
        "camera_username_label": "Username:",
        "camera_password_label": "Password:",
        "camera_ip_label": "Camera IP:",
        "camera_port_label": "Port:",
        "generate_link": "Generate Link",
        "gmt": "GMT:",
        "cutoff_time": "Cutoff Time (HH:MM):",
        "submit": "Submit",
        "invalid_time_format": "Invalid time format. Please enter HH:MM.",
        "cutoff_set_success": "Cutoff time set successfully.",
    }
}
